language: node_js

node_js:
  - 14
  - 12

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-multilib
    - g++-multilib
os:
- osx
- linux
# - windows  # we use appveyor instead
after_script:
- npm run test
- npm run benchmark:small
- npm run benchmark:regular

before_deploy:
- ARCHIVE_NAME="$TRAVIS_OS_NAME.tar"
- npm install
- npm run native:prebuild
# - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm run native:prebuild-ia32; fi
- tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
    node: 12

after_deploy:
- npm run benchmark
