# https://www.appveyor.com/docs/appveyor-yml/
build: off

environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "Current"

configuration: Release
platform:
  - x86
  - x64

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run test
  - npm run benchmark:small
  - npm run benchmark:regular

after_test:
  - ps: If ($env:platform -eq "x64") { npm run native:prebuild }
  - ps: If ($env:platform -eq "x86") { npm run native:prebuild-ia32 }

artifacts:
  - path: prebuilds
    name: win-$(PLATFORM)
    type: zip

deploy:
  provider: GitHub
  auth_token:
    secure: CqG+3BexDw134ePx6KfsoUT59aMH3APg5K0gs6jPiV5KuGOxrSrzpRZWTDiyLGed # your encrypted token from GitHub
  artifact: /.*\.zip/              # upload all zip files to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
    nodejs_version: "12"

after_deploy:
  - npm run benchmark
